### ISSUE TITLE
Reload Index Error

### ISSUE THREAD

**Issue by FredyZarate11** [RFGRONA/BioKudi#3]
- El boton de inicio "BioKudi" presenta fallas cuando el usuario logeado desea ir al Index
![image](https://github.com/RFGRONA/BioKudi/assets/114964703/7890c59b-e55d-4279-900d-26f685b0bfc9)
![image](https://github.com/RFGRONA/BioKudi/assets/114964703/59447355-1707-45ba-8906-b1f4655984df)

**Comment by RFGRONA** [comment]
En la próxima actualización ya estará solucionado. Gracias por el reporte.
